some updates and more functionality
vincentscode/BunnyBotCTF-DiscordBot pull request #2
Opened 2022-04-09 22:13 UTC by THE-ORONCO

No idea why the whole .gitignore file is flagged as changed, but I just added IDE-stuff so that IntelliJ stuff would be ignored.
- used the new match case instead of the elif stuff
- added some consisted formatting to archive.py
- added ctftime.py with the functionality to inspect CTFTime events and also register them as events in discord

2022-04-10 01:09 UTC, vincentscode commented
I think the full-file differences may be due to a difference in line endings (on linux and windows). It would be great if you could fix that as it makes it easier to see what has really been changed.

2022-04-10 13:00 UTC, vincentscode commented
Perfect, way easier to read now!
I am torn on switching to the new match-case statement. It definitely is easier to read but the bot is currently running on Python 3.9 (with match-case being introduced in 3.10). I will check how much work it would be to switch to the newer version.

2022-04-18 11:14 UTC, vincentscode requested changes

2022-04-18 11:14 UTC, vincentscode commented on bot.py
> -intents.message_content = True
Removing this will not work iirc.

2022-04-18 11:14 UTC, vincentscode commented on bot.py
> +    match error:
Please revert back to using if / elif. Upgrading to match/case is currently not easily possible.

2022-04-21 18:31 UTC, THE-ORONCO commented
I changed bot.py back

2022-04-21 18:43 UTC, vincentscode commented
unfortunately it doesn't look like you reverted all the changes

2022-04-21 19:22 UTC, vincentscode commented
Well that seems like a bad idea. 👀

2022-04-21 19:41 UTC, vincentscode approved these changes

2022-04-21 19:41 UTC, merged